# Generated by Django 4.0.6 on 2022-07-23 10:01

from django.db import migrations, models
import django.db.models.deletion
import main.custom_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_tier', models.CharField(max_length=50, unique=True)),
                ('link_to_the_originally_uploaded_file', models.BooleanField(default=False)),
                ('ability_to_generate_expiring_links', models.BooleanField(default=False)),
                ('image_height', models.CharField(default='', max_length=100, validators=[main.custom_models.validate_image_height])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('account_tier', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.accounttiers')),
            ],
        ),
    ]
