# Generated by Django 4.0.6 on 2022-07-23 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttiers',
            old_name='account_tier',
            new_name='account_tier_name',
        ),
        migrations.CreateModel(
            name='OriginalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('width', models.SmallIntegerField(null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('link', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='ModificatedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('width', models.SmallIntegerField(null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('ModificatedImages', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('expiring_time', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)])),
                ('original_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.originalimages')),
            ],
        ),
    ]
