# Generated by Django 4.0.6 on 2022-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_account_tier_accounttiers_account_tier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimages',
            name='link',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
