# Generated by Django 4.0.6 on 2022-07-23 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_originalimages_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('width', models.SmallIntegerField(null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, null=True, unique=True)),
                ('expiring_time', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)])),
                ('images', models.ManyToManyField(to='main.images')),
            ],
        ),
        migrations.RemoveField(
            model_name='originalimages',
            name='user',
        ),
        migrations.DeleteModel(
            name='ModificatedImages',
        ),
        migrations.DeleteModel(
            name='OriginalImages',
        ),
    ]
