# Generated by Django 4.0.6 on 2022-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_images_links_remove_originalimages_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
