# Generated by Django 4.0.6 on 2022-07-26 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_images_expiring_time_images_link_delete_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='OriginalImages',
        ),
        migrations.CreateModel(
            name='ResizeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, unique=True)),
                ('width', models.SmallIntegerField(null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('resize_image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('link', models.CharField(max_length=50, null=True, unique=True)),
                ('expiring_time', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)])),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.originalimages')),
            ],
        ),
    ]
