# Generated by Django 4.0.6 on 2022-07-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_images_originalimages_resizeimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalimages',
            name='link',
        ),
        migrations.RemoveField(
            model_name='resizeimages',
            name='link',
        ),
    ]
