# Generated by Django 4.0.6 on 2022-07-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_originalimages_link_remove_resizeimages_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resizeimages',
            name='image_name',
            field=models.CharField(max_length=50),
        ),
    ]
