# Generated by Django 4.0.6 on 2022-07-31 17:44

from django.db import migrations
import main.custom_models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_resizeimages_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttiers',
            name='image_height',
            field=main.custom_models.IntegerListField(max_length=255, validators=[main.custom_models.validate_image_height]),
        ),
    ]
