# Generated by Django 4.0.6 on 2022-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_accounttiers_image_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimages',
            name='image',
            field=models.ImageField(height_field='height', upload_to='6576a7e45803ab579103c2bfaa6a1ae7', width_field='width'),
        ),
        migrations.AlterField(
            model_name='resizeimages',
            name='resize_image',
            field=models.ImageField(height_field='height', upload_to='91d4bf21ef87815ad2956b9c2ecbe3f5', width_field='width'),
        ),
    ]
