# Generated by Django 4.0.6 on 2022-07-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_originalimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimages',
            name='image',
            field=models.ImageField(height_field='height', upload_to='c57f704b277bcf10e9b8c2a20b6a035b.png', width_field='width'),
        ),
        migrations.AlterField(
            model_name='resizeimages',
            name='resize_image',
            field=models.ImageField(height_field='height', upload_to='3fd7fd49f873f11c8f028a189d69258d.png', width_field='width'),
        ),
    ]
