# Generated by Django 4.0.6 on 2022-07-31 18:47

from django.db import migrations, models
import main.custom_models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_originalimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimages',
            name='image',
            field=models.ImageField(height_field='height', upload_to=main.custom_models.CreateName(), width_field='width'),
        ),
        migrations.AlterField(
            model_name='resizeimages',
            name='resize_image',
            field=models.ImageField(height_field='height', upload_to=main.custom_models.CreateName(), width_field='width'),
        ),
    ]
