# Generated by Django 4.0.6 on 2022-08-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_originalimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalimages',
            name='expiring_time',
        ),
    ]
