# Generated by Django 4.0.6 on 2022-08-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_originalimages_expiring_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimages',
            name='image_name',
            field=models.CharField(max_length=50),
        ),
    ]
