# Generated by Django 4.0.6 on 2022-08-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_originalimages_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.users'),
        ),
    ]
