# Generated by Django 4.0.6 on 2022-08-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_originalimages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resizeimages',
            name='original_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_images', to='main.originalimages'),
        ),
    ]
