# Generated by Django 4.0.6 on 2022-08-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_resizeimages_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.AlterField(
            model_name='resizeimages',
            name='original_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.originalimages'),
        ),
    ]
